from __future__ import annotations

"""Dataset preparation and executable discovery for native text embeddings.

The training loop is C++ and has no Python/Torch dependency.  This module is the
small preparation boundary which turns user-facing tabular datasets into the
indexed, numeric stream consumed by that loop.
"""

import csv
import hashlib
import io
import json
from pathlib import Path
import pickle
import shutil
import struct
from typing import Any, Iterable, Iterator, Mapping, Sequence
import zipfile


EMBEDDING_DATA_VERSION = 1
SUPPORTED_OBJECTIVES = {"raw", "retrieval", "similarity", "class"}
SUPPORTED_FILE_FORMATS = {"txt", "jsonl", "json", "csv", "parquet", "hf"}


def _read_safetensors(path: Path) -> dict[str, tuple[list[int], list[float]]]:
    """Read the float dtypes needed by HF transformer checkpoints without Torch."""
    with path.open("rb") as handle:
        raw_length = handle.read(8)
        if len(raw_length) != 8:
            raise ValueError(f"{path}: truncated safetensors header")
        header_length = struct.unpack("<Q", raw_length)[0]
        header = json.loads(handle.read(header_length))
        payload = handle.read()
    tensors: dict[str, tuple[list[int], list[float]]] = {}
    for name, spec in header.items():
        if name == "__metadata__":
            continue
        dtype = str(spec["dtype"])
        shape = [int(value) for value in spec["shape"]]
        begin, end = (int(value) for value in spec["data_offsets"])
        data = payload[begin:end]
        if dtype == "F32":
            values = list(struct.unpack(f"<{len(data) // 4}f", data))
        elif dtype == "F16":
            values = list(struct.unpack(f"<{len(data) // 2}e", data))
        elif dtype == "BF16":
            words = struct.unpack(f"<{len(data) // 2}H", data)
            values = [struct.unpack("<f", struct.pack("<I", word << 16))[0] for word in words]
        elif dtype in {"I64", "I32", "I16", "I8", "U8", "BOOL"}:
            # HF safetensors may include non-parameter buffers such as
            # position_ids/token_type_ids. They are regenerated by NFN.
            continue
        else:
            raise ValueError(f"{path}: unsupported safetensors dtype {dtype!r} for {name}")
        expected = 1
        for dimension in shape:
            expected *= dimension
        if len(values) != expected:
            raise ValueError(f"{path}: tensor {name} shape/data size mismatch")
        tensors[name] = (shape, values)
    return tensors


class _TorchStorageRef:
    def __init__(self, key: str, dtype: str, size: int) -> None:
        self.key = key
        self.dtype = dtype
        self.size = size


class _TorchTensorRef:
    def __init__(self, storage: _TorchStorageRef, offset: int, shape: Sequence[int], stride: Sequence[int]) -> None:
        self.storage = storage
        self.offset = int(offset)
        self.shape = [int(value) for value in shape]
        self.stride = [int(value) for value in stride]


def _rebuild_torch_tensor(storage: _TorchStorageRef, offset: int, shape: Sequence[int], stride: Sequence[int], *_rest: object) -> _TorchTensorRef:
    return _TorchTensorRef(storage, offset, shape, stride)


class _TorchStateDictUnpickler(pickle.Unpickler):
    _STORAGE_TYPES = {
        "FloatStorage": "F32",
        "HalfStorage": "F16",
        "BFloat16Storage": "BF16",
        "DoubleStorage": "F64",
        "LongStorage": "I64",
        "IntStorage": "I32",
        "ShortStorage": "I16",
        "CharStorage": "I8",
        "ByteStorage": "U8",
        "BoolStorage": "BOOL",
    }

    def find_class(self, module: str, name: str) -> object:
        if module == "collections" and name == "OrderedDict":
            from collections import OrderedDict

            return OrderedDict
        if module == "torch._utils" and name in {"_rebuild_tensor", "_rebuild_tensor_v2", "_rebuild_tensor_v3"}:
            return _rebuild_torch_tensor
        if module == __name__ and name == "_rebuild_torch_tensor":
            return _rebuild_torch_tensor
        if module == "torch" and name in self._STORAGE_TYPES:
            return ("nfn-storage-type", self._STORAGE_TYPES[name])
        raise pickle.UnpicklingError(f"unsupported global in Torch-free state dict: {module}.{name}")

    def persistent_load(self, persistent_id: object) -> _TorchStorageRef:
        if not isinstance(persistent_id, tuple) or len(persistent_id) < 5 or persistent_id[0] != "storage":
            raise pickle.UnpicklingError("unsupported persistent object in Torch-free state dict")
        storage_type = persistent_id[1]
        if not isinstance(storage_type, tuple) or len(storage_type) != 2 or storage_type[0] != "nfn-storage-type":
            raise pickle.UnpicklingError("unsupported storage type in Torch-free state dict")
        return _TorchStorageRef(str(persistent_id[2]), str(storage_type[1]), int(persistent_id[4]))


def _decode_torch_storage(data: bytes, dtype: str) -> list[float] | None:
    if dtype == "F32":
        return list(struct.unpack(f"<{len(data) // 4}f", data))
    if dtype == "F64":
        return [float(value) for value in struct.unpack(f"<{len(data) // 8}d", data)]
    if dtype == "F16":
        return list(struct.unpack(f"<{len(data) // 2}e", data))
    if dtype == "BF16":
        return [struct.unpack("<f", struct.pack("<I", word << 16))[0] for word in struct.unpack(f"<{len(data) // 2}H", data)]
    return None


def _read_pytorch_zip_weights(path: Path) -> dict[str, tuple[list[int], list[float]]]:
    """Read a plain HF PyTorch ZIP state dict with a restricted unpickler."""
    if not zipfile.is_zipfile(path):
        raise ValueError(f"{path}: legacy non-ZIP PyTorch pickle is unsupported; prefer safetensors")
    with zipfile.ZipFile(path) as archive:
        pickle_names = [name for name in archive.namelist() if name.endswith("/data.pkl") or name == "data.pkl"]
        if len(pickle_names) != 1:
            raise ValueError(f"{path}: expected one PyTorch data.pkl")
        pickle_name = pickle_names[0]
        prefix = pickle_name[: -len("data.pkl")]
        state = _TorchStateDictUnpickler(io.BytesIO(archive.read(pickle_name))).load()
        if not isinstance(state, Mapping):
            raise ValueError(f"{path}: PyTorch checkpoint root is not a state dict")
        storage_cache: dict[tuple[str, str], list[float] | None] = {}
        tensors: dict[str, tuple[list[int], list[float]]] = {}
        for name, tensor in state.items():
            if not isinstance(name, str) or not isinstance(tensor, _TorchTensorRef):
                continue
            storage_key = (tensor.storage.key, tensor.storage.dtype)
            if storage_key not in storage_cache:
                storage_name = prefix + "data/" + tensor.storage.key
                if storage_name not in archive.namelist():
                    raise ValueError(f"{path}: missing PyTorch storage {storage_name}")
                storage_cache[storage_key] = _decode_torch_storage(archive.read(storage_name), tensor.storage.dtype)
            storage = storage_cache[storage_key]
            if storage is None:
                continue
            count = 1
            for dimension in tensor.shape:
                count *= dimension
            values: list[float] = []
            for flat_index in range(count):
                remainder = flat_index
                storage_index = tensor.offset
                for dimension, stride in zip(reversed(tensor.shape), reversed(tensor.stride)):
                    coordinate = remainder % dimension
                    remainder //= dimension
                    storage_index += coordinate * stride
                if storage_index < 0 or storage_index >= len(storage):
                    raise ValueError(f"{path}: tensor {name} indexes beyond its storage")
                values.append(storage[storage_index])
            tensors[name] = (tensor.shape, values)
    return tensors


def _resolve_hf_model(source: str, revision: str | None = None) -> Path:
    local = Path(source).expanduser()
    if local.exists():
        return local.resolve()
    try:
        from huggingface_hub import snapshot_download
    except ImportError as exc:
        raise RuntimeError("Hugging Face model IDs require `pip install neuralfn[embeddings]`") from exc
    return Path(
        snapshot_download(
            source,
            revision=revision,
            allow_patterns=["config.json", "*.safetensors", "*.safetensors.index.json", "pytorch_model*.bin", "pytorch_model*.bin.index.json", "tokenizer*", "vocab*", "merges.txt", "special_tokens_map.json"],
        )
    ).resolve()


def _find_tensor(tensors: Mapping[str, tuple[list[int], list[float]]], *suffixes: str, required: bool = True) -> tuple[list[int], list[float]] | None:
    for suffix in suffixes:
        matches = [(name, tensor) for name, tensor in tensors.items() if name == suffix or name.endswith("." + suffix)]
        if matches:
            return sorted(matches, key=lambda item: (len(item[0]), item[0]))[0][1]
    if required:
        raise ValueError(f"Hugging Face checkpoint is missing tensor suffixes: {', '.join(suffixes)}")
    return None


def _identity(size: int) -> list[float]:
    values = [0.0] * (size * size)
    for index in range(size):
        values[index * size + index] = 1.0
    return values


def _hf_special_token_id(model_dir: Path, config: Mapping[str, Any], name: str, fallback: int) -> int:
    configured_id = config.get(f"{name}_token_id")
    if configured_id is not None:
        return int(configured_id)
    token: str | None = None
    for filename in ("tokenizer_config.json", "special_tokens_map.json"):
        path = model_dir / filename
        if not path.is_file():
            continue
        raw = json.loads(path.read_text(encoding="utf-8")).get(f"{name}_token")
        if isinstance(raw, str):
            token = raw
        elif isinstance(raw, Mapping):
            token = str(raw.get("content", "")) or None
        if token:
            break
    if token is None and name == "mask":
        token = "[MASK]"
    vocab_txt = model_dir / "vocab.txt"
    if token and vocab_txt.is_file():
        vocab = {piece: index for index, piece in enumerate(vocab_txt.read_text(encoding="utf-8").splitlines())}
        if token in vocab:
            return vocab[token]
    vocab_json = model_dir / "vocab.json"
    if token and vocab_json.is_file():
        vocab = json.loads(vocab_json.read_text(encoding="utf-8"))
        if token in vocab:
            return int(vocab[token])
    tokenizer_json = model_dir / "tokenizer.json"
    if token and tokenizer_json.is_file():
        model_vocab = json.loads(tokenizer_json.read_text(encoding="utf-8")).get("model", {}).get("vocab", {})
        if isinstance(model_vocab, Mapping) and token in model_vocab:
            return int(model_vocab[token])
        if isinstance(model_vocab, list):
            for index, entry in enumerate(model_vocab):
                if isinstance(entry, list) and entry and entry[0] == token:
                    return index
    return fallback


def _transpose(values: Sequence[float], rows: int, columns: int) -> list[float]:
    return [float(values[row * columns + column]) for column in range(columns) for row in range(rows)]


def _write_float_vector(handle: Any, values: Sequence[float]) -> None:
    handle.write(struct.pack("<Q", len(values)))
    if values:
        handle.write(struct.pack(f"<{len(values)}f", *values))


def import_huggingface_embedding_model(
    source: str,
    output_path: str | Path,
    *,
    revision: str | None = None,
    pooling: str = "mean",
    normalize: bool = True,
) -> dict[str, Any]:
    """Import a BERT-family or GPT-2-family safetensors model into NFNEMB2.

    Prefixes are deliberately shape/suffix based, so wrappers such as
    ``model.bert.*`` and Sentence Transformers' ``0_Transformer.*`` work too.
    """
    model_dir = _resolve_hf_model(source, revision)
    config = json.loads((model_dir / "config.json").read_text(encoding="utf-8"))
    tensor_files = sorted(model_dir.glob("*.safetensors"))
    pytorch_files = sorted(model_dir.glob("pytorch_model*.bin")) if not tensor_files else []
    if not tensor_files and not pytorch_files:
        raise ValueError(f"{model_dir}: no safetensors or PyTorch ZIP state-dict weights found")
    tensors: dict[str, tuple[list[int], list[float]]] = {}
    for tensor_file in tensor_files:
        tensors.update(_read_safetensors(tensor_file))
    for tensor_file in pytorch_files:
        tensors.update(_read_pytorch_zip_weights(tensor_file))

    model_type = str(config.get("model_type", "")).lower()
    is_gpt = model_type in {"gpt2", "gpt_bigcode", "openai-gpt"} or any(name.endswith("transformer.wte.weight") or name == "wte.weight" for name in tensors)
    architecture = "gpt-derived" if is_gpt else "bert"
    hidden = int(config.get("hidden_size", config.get("n_embd", config.get("dim", 0))))
    layers = int(config.get("num_hidden_layers", config.get("n_layer", config.get("n_layers", 0))))
    heads = int(config.get("num_attention_heads", config.get("n_head", config.get("n_heads", 0))))
    intermediate = int(
        (config.get("n_inner") or hidden * 4)
        if is_gpt
        else config.get("intermediate_size", config.get("hidden_dim", hidden * 4))
    )
    max_tokens = int(config.get("max_position_embeddings", config.get("n_positions", 0)))
    vocab = int(config.get("vocab_size", 0))
    activation_name = str(config.get("activation_function", config.get("hidden_act", config.get("activation", "gelu")))).lower()
    activation = "gelu-tanh" if activation_name in {"gelu_new", "gelu_fast", "gelu_pytorch_tanh"} else "gelu"
    layer_norm_epsilon = float(config.get("layer_norm_eps", config.get("layer_norm_epsilon", 1e-5 if is_gpt else 1e-12)))
    mask_token_id = _hf_special_token_id(
        model_dir,
        config,
        "mask",
        int((config.get("eos_token_id") or 1) if is_gpt else 1),
    )
    if min(hidden, layers, heads, intermediate, max_tokens, vocab) <= 0 or hidden % heads:
        raise ValueError(f"{model_dir}: incomplete or invalid transformer geometry in config.json")

    empty: list[float] = []
    linears: list[tuple[list[float], list[float]]] = []
    if architecture == "bert":
        token_shape, token = _find_tensor(tensors, "embeddings.word_embeddings.weight")  # type: ignore[misc]
        position_shape, position = _find_tensor(tensors, "embeddings.position_embeddings.weight")  # type: ignore[misc]
        token_type_tensor = _find_tensor(tensors, "embeddings.token_type_embeddings.weight", required=False)
        token_type = list(token_type_tensor[1]) if token_type_tensor else [0.0] * (2 * hidden)
        if len(token_type) < 2 * hidden:
            token_type.extend([0.0] * (2 * hidden - len(token_type)))
        token_type = token_type[: 2 * hidden]
        embedding_ln_weight = list(_find_tensor(tensors, "embeddings.LayerNorm.weight")[1])  # type: ignore[index]
        embedding_ln_bias = list(_find_tensor(tensors, "embeddings.LayerNorm.bias")[1])  # type: ignore[index]
        if token_shape != [vocab, hidden] or len(position_shape) != 2 or position_shape[0] < max_tokens or position_shape[1] != hidden:
            raise ValueError("Hugging Face embedding tensor shapes do not match config.json")
        position = list(position[: max_tokens * hidden])
        distilbert_layout = any(name.endswith("transformer.layer.0.attention.q_lin.weight") for name in tensors)
        for layer in range(layers):
            prefix = f"transformer.layer.{layer}" if distilbert_layout else f"encoder.layer.{layer}"
            if distilbert_layout:
                norm_suffixes = (
                    f"{prefix}.sa_layer_norm.weight", f"{prefix}.sa_layer_norm.bias",
                    f"{prefix}.output_layer_norm.weight", f"{prefix}.output_layer_norm.bias",
                )
                linear_suffixes = (
                    (f"{prefix}.attention.q_lin.weight", f"{prefix}.attention.q_lin.bias"),
                    (f"{prefix}.attention.k_lin.weight", f"{prefix}.attention.k_lin.bias"),
                    (f"{prefix}.attention.v_lin.weight", f"{prefix}.attention.v_lin.bias"),
                    (f"{prefix}.attention.out_lin.weight", f"{prefix}.attention.out_lin.bias"),
                    (f"{prefix}.ffn.lin1.weight", f"{prefix}.ffn.lin1.bias"),
                    (f"{prefix}.ffn.lin2.weight", f"{prefix}.ffn.lin2.bias"),
                )
            else:
                norm_suffixes = (
                    f"{prefix}.attention.output.LayerNorm.weight", f"{prefix}.attention.output.LayerNorm.bias",
                    f"{prefix}.output.LayerNorm.weight", f"{prefix}.output.LayerNorm.bias",
                )
                linear_suffixes = (
                    (f"{prefix}.attention.self.query.weight", f"{prefix}.attention.self.query.bias"),
                    (f"{prefix}.attention.self.key.weight", f"{prefix}.attention.self.key.bias"),
                    (f"{prefix}.attention.self.value.weight", f"{prefix}.attention.self.value.bias"),
                    (f"{prefix}.attention.output.dense.weight", f"{prefix}.attention.output.dense.bias"),
                    (f"{prefix}.intermediate.dense.weight", f"{prefix}.intermediate.dense.bias"),
                    (f"{prefix}.output.dense.weight", f"{prefix}.output.dense.bias"),
                )
            ln1w = list(_find_tensor(tensors, norm_suffixes[0])[1])  # type: ignore[index]
            ln1b = list(_find_tensor(tensors, norm_suffixes[1])[1])  # type: ignore[index]
            ln2w = list(_find_tensor(tensors, norm_suffixes[2])[1])  # type: ignore[index]
            ln2b = list(_find_tensor(tensors, norm_suffixes[3])[1])  # type: ignore[index]
            block: list[tuple[list[float], list[float]]] = []
            expected_shapes = ([hidden, hidden], [hidden, hidden], [hidden, hidden], [hidden, hidden], [intermediate, hidden], [hidden, intermediate])
            for (weight_suffix, bias_suffix), expected_shape in zip(linear_suffixes, expected_shapes):
                weight_shape, weight = _find_tensor(tensors, weight_suffix)  # type: ignore[misc]
                bias_shape, bias = _find_tensor(tensors, bias_suffix)  # type: ignore[misc]
                if weight_shape != expected_shape or bias_shape != [expected_shape[0]]:
                    raise ValueError(f"HF tensor {weight_suffix} has shape {weight_shape}; expected {expected_shape}")
                block.append((list(weight), list(bias)))
            linears.extend(block)
            config.setdefault("_nfn_layer_norms", []).append((ln1w, ln1b, ln2w, ln2b))
        final_ln_weight, final_ln_bias = [1.0] * hidden, [0.0] * hidden
    else:
        token_shape, token = _find_tensor(tensors, "transformer.wte.weight", "wte.weight")  # type: ignore[misc]
        position_shape, position = _find_tensor(tensors, "transformer.wpe.weight", "wpe.weight")  # type: ignore[misc]
        token_type, embedding_ln_weight, embedding_ln_bias = empty, [1.0] * hidden, [0.0] * hidden
        if token_shape != [vocab, hidden] or len(position_shape) != 2 or position_shape[0] < max_tokens or position_shape[1] != hidden:
            raise ValueError("Hugging Face GPT embedding tensor shapes do not match config.json")
        position = list(position[: max_tokens * hidden])
        for layer in range(layers):
            prefix = f"transformer.h.{layer}"
            ln1w = list(_find_tensor(tensors, f"{prefix}.ln_1.weight", f"h.{layer}.ln_1.weight")[1])  # type: ignore[index]
            ln1b = list(_find_tensor(tensors, f"{prefix}.ln_1.bias", f"h.{layer}.ln_1.bias")[1])  # type: ignore[index]
            ln2w = list(_find_tensor(tensors, f"{prefix}.ln_2.weight", f"h.{layer}.ln_2.weight")[1])  # type: ignore[index]
            ln2b = list(_find_tensor(tensors, f"{prefix}.ln_2.bias", f"h.{layer}.ln_2.bias")[1])  # type: ignore[index]
            c_attn_tensor = _find_tensor(tensors, f"{prefix}.attn.c_attn.weight", f"h.{layer}.attn.c_attn.weight", required=False)
            conv1d_layout = c_attn_tensor is not None
            if conv1d_layout:
                c_attn_shape, c_attn = c_attn_tensor
                _, c_attn_bias = _find_tensor(tensors, f"{prefix}.attn.c_attn.bias", f"h.{layer}.attn.c_attn.bias")  # type: ignore[misc]
                if c_attn_shape != [hidden, 3 * hidden]:
                    raise ValueError(f"GPT layer {layer} c_attn must have shape [{hidden}, {3 * hidden}]")
                for part in range(3):
                    weight = [float(c_attn[input_index * 3 * hidden + part * hidden + output_index]) for output_index in range(hidden) for input_index in range(hidden)]
                    bias = list(c_attn_bias[part * hidden : (part + 1) * hidden])
                    linears.append((weight, bias))
                output_weight_suffix = f"{prefix}.attn.c_proj.weight"
                output_bias_suffix = f"{prefix}.attn.c_proj.bias"
            else:
                for projection_name in ("q_proj", "k_proj", "v_proj"):
                    weight_shape, weight_values = _find_tensor(tensors, f"{prefix}.attn.attention.{projection_name}.weight")  # type: ignore[misc]
                    if weight_shape != [hidden, hidden]:
                        raise ValueError(f"GPT layer {layer} {projection_name} has shape {weight_shape}; expected [{hidden}, {hidden}]")
                    weight = list(weight_values)
                    bias_tensor = _find_tensor(tensors, f"{prefix}.attn.attention.{projection_name}.bias", required=False)
                    linears.append((weight, list(bias_tensor[1]) if bias_tensor else [0.0] * hidden))
                output_weight_suffix = f"{prefix}.attn.attention.out_proj.weight"
                output_bias_suffix = f"{prefix}.attn.attention.out_proj.bias"
            for weight_suffix, bias_suffix, input_dim, output_dim in (
                (output_weight_suffix, output_bias_suffix, hidden, hidden),
                (f"{prefix}.mlp.c_fc.weight", f"{prefix}.mlp.c_fc.bias", hidden, intermediate),
                (f"{prefix}.mlp.c_proj.weight", f"{prefix}.mlp.c_proj.bias", intermediate, hidden),
            ):
                shape, weight = _find_tensor(tensors, weight_suffix, weight_suffix.removeprefix("transformer."))  # type: ignore[misc]
                bias_tensor = _find_tensor(tensors, bias_suffix, bias_suffix.removeprefix("transformer."), required=False)
                bias = list(bias_tensor[1]) if bias_tensor else [0.0] * output_dim
                if conv1d_layout and shape == [input_dim, output_dim]:
                    weight = _transpose(weight, input_dim, output_dim)
                elif shape != [output_dim, input_dim]:
                    raise ValueError(f"GPT tensor {weight_suffix} has unsupported shape {shape}")
                linears.append((list(weight), list(bias)))
            config.setdefault("_nfn_layer_norms", []).append((ln1w, ln1b, ln2w, ln2b))
        final_ln_weight = list(_find_tensor(tensors, "transformer.ln_f.weight", "ln_f.weight")[1])  # type: ignore[index]
        final_ln_bias = list(_find_tensor(tensors, "transformer.ln_f.bias", "ln_f.bias")[1])  # type: ignore[index]

    destination = Path(output_path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    pooling_code = {"mean": 0, "cls": 1, "last": 2}[pooling]
    header = [2, vocab, hidden, hidden, max_tokens, 0, 0, int(architecture == "gpt-derived"), pooling_code, int(normalize), layers, heads, intermediate, 16, int(activation == "gelu-tanh"), mask_token_id]
    with destination.open("wb") as handle:
        handle.write(b"NFNEMB2\0")
        handle.write(struct.pack("<16I", *header))
        handle.write(struct.pack("<4f", 0.2, 32.0, 0.05, layer_norm_epsilon))
        for values in (token, position, token_type, embedding_ln_weight, embedding_ln_bias):
            _write_float_vector(handle, values)
        linear_index = 0
        for norms in config.pop("_nfn_layer_norms"):
            for values in norms:
                _write_float_vector(handle, values)
            for _ in range(6):
                weight, bias = linears[linear_index]
                linear_index += 1
                for values in (weight, bias, empty, empty):
                    _write_float_vector(handle, values)
        for values in (final_ln_weight, final_ln_bias, _identity(hidden), [0.0] * hidden, empty, empty):
            _write_float_vector(handle, values)

    copied_tokenizer_files: list[str] = []
    for name in ("tokenizer.json", "tokenizer_config.json", "special_tokens_map.json", "vocab.txt", "vocab.json", "merges.txt"):
        source_file = model_dir / name
        if source_file.is_file():
            target = destination.parent / name
            if source_file.resolve() != target.resolve():
                shutil.copy2(source_file, target)
            copied_tokenizer_files.append(name)
    metadata = {
        "format": "nfn_embedding_hf_import_v1",
        "source": source,
        "revision": revision,
        "checkpoint": str(destination),
        "architecture": architecture,
        "vocab_size": vocab,
        "hidden_dim": hidden,
        "output_dim": hidden,
        "max_tokens": max_tokens,
        "num_layers": layers,
        "num_heads": heads,
        "intermediate_dim": intermediate,
        "activation": activation,
        "layer_norm_epsilon": layer_norm_epsilon,
        "mask_token_id": mask_token_id,
        "tokenizer_files": copied_tokenizer_files,
        "tensor_count": len(tensors),
        "source_weight_format": "safetensors" if tensor_files else "pytorch-zip-state-dict",
    }
    (destination.parent / "embedding_import.json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return metadata


def stable_token_id(token: str, vocab_size: int) -> int:
    """Return the native trainer's stable FNV-1a token id."""
    if vocab_size < 4:
        raise ValueError("embedding vocab size must be at least 4")
    value = 2166136261
    for byte in token.encode("utf-8"):
        value ^= byte
        value = (value * 16777619) & 0xFFFFFFFF
    return 3 + value % (vocab_size - 3)


def tokenize_embedding_text(text: object, *, vocab_size: int, max_tokens: int) -> list[int]:
    tokens = [stable_token_id(piece, vocab_size) for piece in str(text).lower().split()]
    return tokens[:max_tokens] or [2]


def tokenize_huggingface_text(text: object, tokenizer_dir: str | Path, *, max_tokens: int) -> list[int]:
    """Tokenize with copied HF tokenizer assets without importing Torch."""
    root = Path(tokenizer_dir)
    tokenizer_json = root / "tokenizer.json"
    if tokenizer_json.is_file():
        try:
            from tokenizers import Tokenizer
        except ImportError as exc:
            if not (root / "vocab.txt").is_file():
                raise RuntimeError("tokenizer.json requires `pip install neuralfn[embeddings]`") from exc
        else:
            return Tokenizer.from_file(str(tokenizer_json)).encode(str(text), add_special_tokens=True).ids[:max_tokens]
    vocab_path = root / "vocab.txt"
    if not vocab_path.is_file():
        raise ValueError(f"{root}: imported model has no tokenizer.json or vocab.txt")
    vocab = {token: index for index, token in enumerate(vocab_path.read_text(encoding="utf-8").splitlines())}
    config_path = root / "tokenizer_config.json"
    config = json.loads(config_path.read_text(encoding="utf-8")) if config_path.is_file() else {}
    unknown = int(vocab.get(str(config.get("unk_token", "[UNK]")), vocab.get("[UNK]", 0)))
    pieces: list[int] = []
    cls_token = str(config.get("cls_token", "[CLS]"))
    sep_token = str(config.get("sep_token", "[SEP]"))
    if cls_token in vocab:
        pieces.append(vocab[cls_token])
    normalized = str(text).lower() if config.get("do_lower_case", True) else str(text)
    for word in normalized.split():
        start = 0
        word_pieces: list[int] = []
        while start < len(word):
            end = len(word)
            found: int | None = None
            while end > start:
                candidate = word[start:end] if start == 0 else "##" + word[start:end]
                if candidate in vocab:
                    found = vocab[candidate]
                    break
                end -= 1
            if found is None:
                word_pieces = [unknown]
                break
            word_pieces.append(found)
            start = end
        pieces.extend(word_pieces)
    if sep_token in vocab:
        pieces.append(vocab[sep_token])
    return pieces[:max_tokens] or [unknown]


def _json_records(path: Path) -> Iterator[Mapping[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, list):
        records = payload
    elif isinstance(payload, dict):
        records = payload.get("data", payload.get("records", [payload]))
    else:
        raise ValueError(f"{path}: JSON dataset must be an object or array")
    if not isinstance(records, list):
        raise ValueError(f"{path}: data/records must be an array")
    for index, record in enumerate(records, start=1):
        if not isinstance(record, Mapping):
            raise ValueError(f"{path}: record {index} is not an object")
        yield record


def _file_records(path: Path, fmt: str, split: str) -> Iterator[Mapping[str, Any]]:
    if fmt == "txt":
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                yield {"text": line.strip()}
        return
    if fmt == "jsonl":
        with path.open(encoding="utf-8") as handle:
            for line_number, line in enumerate(handle, start=1):
                if not line.strip():
                    continue
                record = json.loads(line)
                if not isinstance(record, Mapping):
                    raise ValueError(f"{path}:{line_number}: JSONL record must be an object")
                yield record
        return
    if fmt == "json":
        yield from _json_records(path)
        return
    if fmt == "csv":
        with path.open(encoding="utf-8", newline="") as handle:
            yield from csv.DictReader(handle)
        return
    if fmt == "parquet":
        try:
            from datasets import load_dataset
        except ImportError as exc:
            raise RuntimeError("Parquet embedding datasets require `pip install neuralfn[datasets]`") from exc
        yield from load_dataset("parquet", data_files=str(path), split="train")
        return
    if fmt == "hf":
        try:
            from datasets import load_dataset
        except ImportError as exc:
            raise RuntimeError("Hugging Face embedding datasets require `pip install neuralfn[datasets]`") from exc
        yield from load_dataset(str(path), split=split)
        return
    raise ValueError(f"unsupported embedding dataset format: {fmt}")


def load_embedding_manifest(path: str | Path) -> dict[str, Any]:
    manifest_path = Path(path).expanduser().resolve()
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    if isinstance(payload, list):
        payload = {"datasets": payload}
    if not isinstance(payload, dict) or not isinstance(payload.get("datasets"), list):
        raise ValueError("embedding dataset manifest must contain a datasets array")
    payload = dict(payload)
    payload["_manifest_path"] = str(manifest_path)
    return payload


def _dataset_format(source: str, explicit: object) -> str:
    if explicit:
        return str(explicit).strip().lower()
    suffix = Path(source).suffix.lower().lstrip(".")
    return suffix if suffix in SUPPORTED_FILE_FORMATS else "hf"


def _field(record: Mapping[str, Any], columns: Mapping[str, Any], logical: str, aliases: Sequence[str]) -> Any:
    requested = str(columns.get(logical, "") or "").strip()
    candidates = [requested] if requested else list(aliases)
    for candidate in candidates:
        if candidate in record:
            return record[candidate]
    return None


def _ids(
    value: object,
    *,
    vocab_size: int,
    max_tokens: int,
    tokenizer_dir: str | Path | None = None,
    prepend_cls: bool = False,
) -> str:
    tokens = (
        tokenize_huggingface_text(value, tokenizer_dir, max_tokens=max_tokens)
        if tokenizer_dir is not None
        else tokenize_embedding_text(value, vocab_size=vocab_size, max_tokens=max(1, max_tokens - int(prepend_cls)))
    )
    if tokenizer_dir is None and prepend_cls:
        tokens = ([2] + ([] if tokens == [2] else tokens))[:max_tokens]
    return ",".join(str(token) for token in tokens)


def _float(value: object, *, field: str, context: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{context}: {field} must be numeric") from exc


def compile_embedding_datasets(
    manifest: str | Path | Mapping[str, Any],
    output_path: str | Path,
    *,
    vocab_size: int = 32768,
    max_tokens: int = 128,
    tokenizer_dir: str | Path | None = None,
    architecture: str = "bert",
) -> dict[str, Any]:
    """Compile a multi-dataset manifest into the native numeric stream."""
    if architecture not in {"bert", "gpt-derived"}:
        raise ValueError("embedding architecture must be bert or gpt-derived")
    prepend_cls = tokenizer_dir is None and architecture == "bert"
    payload = load_embedding_manifest(manifest) if isinstance(manifest, (str, Path)) else dict(manifest)
    datasets = payload.get("datasets")
    if not isinstance(datasets, list) or not datasets:
        raise ValueError("embedding dataset manifest requires at least one dataset")
    manifest_path = Path(str(payload.get("_manifest_path", ""))) if payload.get("_manifest_path") else None
    base_dir = manifest_path.parent if manifest_path else Path.cwd()
    destination = Path(output_path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# nfn_embedding_indexed_v{EMBEDDING_DATA_VERSION}\tvocab={vocab_size}\tmax_tokens={max_tokens}"]
    counts: dict[str, int] = {}
    dataset_summaries: list[dict[str, Any]] = []
    for dataset_index, raw_spec in enumerate(datasets):
        if not isinstance(raw_spec, Mapping):
            raise ValueError(f"dataset entry {dataset_index} must be an object")
        spec = dict(raw_spec)
        source = str(spec.get("source", "")).strip()
        if not source:
            raise ValueError(f"dataset entry {dataset_index} is missing source")
        objective = str(spec.get("objective", "raw")).strip().lower()
        if objective not in SUPPORTED_OBJECTIVES:
            raise ValueError(f"dataset entry {dataset_index}: unsupported objective {objective!r}")
        fmt = _dataset_format(source, spec.get("format"))
        if fmt not in SUPPORTED_FILE_FORMATS:
            raise ValueError(f"dataset entry {dataset_index}: unsupported format {fmt!r}")
        source_path = Path(source).expanduser()
        if fmt != "hf" and not source_path.is_absolute():
            source_path = (base_dir / source_path).resolve()
        resolved_source = str(source_path) if fmt != "hf" else source
        columns = spec.get("columns") or {}
        if not isinstance(columns, Mapping):
            raise ValueError(f"dataset entry {dataset_index}: columns must be an object")
        weight = _float(spec.get("weight", 1.0), field="weight", context=f"dataset {dataset_index}")
        loss_weight = _float(spec.get("loss_weight", 1.0), field="loss_weight", context=f"dataset {dataset_index}")
        if weight <= 0 or loss_weight < 0:
            raise ValueError(f"dataset entry {dataset_index}: weight must be > 0 and loss_weight >= 0")
        score_min = _float(spec.get("score_min", 0.0), field="score_min", context=f"dataset {dataset_index}")
        score_max = _float(spec.get("score_max", 1.0), field="score_max", context=f"dataset {dataset_index}")
        if objective == "similarity" and score_max <= score_min:
            raise ValueError(f"dataset entry {dataset_index}: score_max must exceed score_min")
        count = 0
        label_ids: dict[str, int] = {}
        for row_number, record in enumerate(_file_records(Path(resolved_source), fmt, str(spec.get("split", "train"))), start=1):
            context = f"{source}:{row_number}"
            first = second = ""
            negatives = ""
            label = -1
            score = 0.0
            if objective == "raw":
                text = _field(record, columns, "text", ("text", "sentence", "document", "content"))
                if text is None:
                    raise ValueError(f"{context}: raw objective requires a text column")
                first = _ids(text, vocab_size=vocab_size, max_tokens=max_tokens, tokenizer_dir=tokenizer_dir, prepend_cls=prepend_cls)
            elif objective == "retrieval":
                query = _field(record, columns, "query", ("query", "anchor", "question"))
                positive = _field(record, columns, "positive", ("positive", "document", "passage", "answer"))
                if query is None or positive is None:
                    raise ValueError(f"{context}: retrieval objective requires query and positive columns")
                first = _ids(query, vocab_size=vocab_size, max_tokens=max_tokens, tokenizer_dir=tokenizer_dir, prepend_cls=prepend_cls)
                second = _ids(positive, vocab_size=vocab_size, max_tokens=max_tokens, tokenizer_dir=tokenizer_dir, prepend_cls=prepend_cls)
                raw_negatives = _field(record, columns, "negatives", ("negatives", "hard_negatives", "negative"))
                if raw_negatives is not None:
                    values = raw_negatives if isinstance(raw_negatives, list) else [raw_negatives]
                    negatives = ";".join(_ids(value, vocab_size=vocab_size, max_tokens=max_tokens, tokenizer_dir=tokenizer_dir, prepend_cls=prepend_cls) for value in values)
            elif objective == "similarity":
                left = _field(record, columns, "sentence1", ("sentence1", "text1", "anchor"))
                right = _field(record, columns, "sentence2", ("sentence2", "text2", "positive"))
                raw_score = _field(record, columns, "score", ("score", "similarity", "label"))
                if left is None or right is None or raw_score is None:
                    raise ValueError(f"{context}: similarity objective requires sentence1, sentence2, and score")
                first = _ids(left, vocab_size=vocab_size, max_tokens=max_tokens, tokenizer_dir=tokenizer_dir, prepend_cls=prepend_cls)
                second = _ids(right, vocab_size=vocab_size, max_tokens=max_tokens, tokenizer_dir=tokenizer_dir, prepend_cls=prepend_cls)
                score = 2.0 * (_float(raw_score, field="score", context=context) - score_min) / (score_max - score_min) - 1.0
                score = max(-1.0, min(1.0, score))
            else:
                text = _field(record, columns, "text", ("text", "sentence", "document"))
                raw_label = _field(record, columns, "label", ("label", "class", "category"))
                if text is None or raw_label is None:
                    raise ValueError(f"{context}: class objective requires text and label columns")
                first = _ids(text, vocab_size=vocab_size, max_tokens=max_tokens, tokenizer_dir=tokenizer_dir, prepend_cls=prepend_cls)
                label_key = str(raw_label)
                label = label_ids.setdefault(label_key, len(label_ids))
            lines.append(
                "\t".join(
                    (str(dataset_index), objective, f"{weight:.9g}", f"{loss_weight:.9g}", str(label), f"{score:.9g}", first, second, negatives)
                )
            )
            count += 1
        if count == 0:
            raise ValueError(f"dataset entry {dataset_index}: no usable records")
        counts[objective] = counts.get(objective, 0) + count
        dataset_summaries.append({
            "index": dataset_index,
            "name": str(spec.get("name") or spec.get("topic") or f"dataset-{dataset_index}"),
            "source": source,
            "format": fmt,
            "objective": objective,
            "weight": weight,
            "loss_weight": loss_weight,
            "records": count,
        })
    encoded = ("\n".join(lines) + "\n").encode("utf-8")
    destination.write_bytes(encoded)
    metadata = {
        "format": f"embedding_indexed_v{EMBEDDING_DATA_VERSION}",
        "path": str(destination),
        "sha256": hashlib.sha256(encoded).hexdigest(),
        "vocab_size": vocab_size,
        "max_tokens": max_tokens,
        "tokenizer": str(Path(tokenizer_dir).resolve()) if tokenizer_dir is not None else "native-hash",
        "prepend_cls": prepend_cls,
        "architecture": architecture,
        "records": sum(counts.values()),
        "objectives": counts,
        "datasets": dataset_summaries,
    }
    destination.with_suffix(destination.suffix + ".json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return metadata


def inline_embedding_manifest(sources: Iterable[str], *, objective: str = "raw") -> dict[str, Any]:
    return {
        "datasets": [
            {"name": Path(source).stem or f"dataset-{index}", "source": source, "objective": objective, "weight": 1.0}
            for index, source in enumerate(sources)
        ]
    }


def resolve_native_embedding_cli(repo_root: str | Path | None = None) -> str:
    import os
    import shutil

    requested = os.environ.get("NFN_NATIVE_EMBEDDING_CLI", "").strip()
    if requested:
        return requested
    root = Path(repo_root).resolve() if repo_root is not None else Path(__file__).resolve().parents[1]
    built = root / "build" / "nfn_embedding_native_train"
    if built.exists():
        return str(built)
    return shutil.which("nfn_embedding_native_train") or str(built)


def prepare_embedding_training_command(command: Sequence[str], *, repo_root: str | Path) -> tuple[list[str], dict[str, Any] | None]:
    """Replace user dataset arguments with a compiled stream for the C++ loop."""
    args = list(command)
    has_compiled_data = "--embedding-data" in args or any(item.startswith("--embedding-data=") for item in args)

    def values(flag: str) -> list[str]:
        found: list[str] = []
        index = 1
        while index < len(args):
            item = args[index]
            if item == flag and index + 1 < len(args):
                found.append(args[index + 1])
                index += 2
            elif item.startswith(flag + "="):
                found.append(item.split("=", 1)[1])
                index += 1
            else:
                index += 1
        return found

    manifests = values("--embedding-datasets-manifest")
    sources = values("--embedding-dataset")
    if has_compiled_data and (manifests or sources):
        raise ValueError("use --embedding-data or manifest/source inputs, not both")
    if not has_compiled_data and not manifests and not sources:
        raise ValueError("embedding training requires --embedding-datasets-manifest PATH or at least one --embedding-dataset PATH")
    if len(manifests) > 1 or (manifests and sources):
        raise ValueError("use one embedding dataset manifest or repeated inline datasets, not both")
    output_values = values("--output-dir")
    output_dir = Path(output_values[-1] if output_values else Path(repo_root) / "artifacts" / "embedding").expanduser().resolve()

    def replace_option(flag: str, value: object) -> None:
        nonlocal args
        replaced: list[str] = []
        index = 0
        while index < len(args):
            item = args[index]
            if item == flag:
                if index + 1 >= len(args):
                    raise ValueError(f"{flag} requires a value")
                index += 2
                continue
            if item.startswith(flag + "="):
                index += 1
                continue
            replaced.append(item)
            index += 1
        replaced.extend([flag, str(value)])
        args = replaced

    tokenizer_dir: Path | None = None
    import_metadata: dict[str, Any] | None = None
    hf_models = values("--embedding-hf-model")
    hf_revisions = values("--embedding-hf-revision")
    if len(hf_models) > 1 or len(hf_revisions) > 1:
        raise ValueError("embedding training accepts one Hugging Face base model and revision")
    if hf_models:
        if values("--base-checkpoint"):
            raise ValueError("use --embedding-hf-model or --base-checkpoint, not both")
        imported_checkpoint = output_dir / "hf_import" / "embedding_model.bin"
        import_metadata = import_huggingface_embedding_model(
            hf_models[0],
            imported_checkpoint,
            revision=hf_revisions[0] if hf_revisions else None,
            pooling=(values("--pooling") or ["mean"])[-1],
        )
        tokenizer_dir = imported_checkpoint.parent
        replace_option("--base-checkpoint", imported_checkpoint)
        for flag, key in (
            ("--embedding-architecture", "architecture"),
            ("--embedding-vocab-size", "vocab_size"),
            ("--hidden-dim", "hidden_dim"),
            ("--embedding-dim", "output_dim"),
            ("--max-seq-len", "max_tokens"),
            ("--num-layers", "num_layers"),
            ("--num-heads", "num_heads"),
            ("--intermediate-dim", "intermediate_dim"),
            ("--activation", "activation"),
            ("--layer-norm-epsilon", "layer_norm_epsilon"),
            ("--mask-token-id", "mask_token_id"),
        ):
            replace_option(flag, import_metadata[key])
        if has_compiled_data:
            compiled_path = Path(values("--embedding-data")[-1]).expanduser()
            with compiled_path.open(encoding="utf-8") as handle:
                data_header = handle.readline().strip()
            expected_fragment = f"vocab={import_metadata['vocab_size']}"
            if not data_header.startswith("# nfn_embedding_indexed_v") or expected_fragment not in data_header.split("\t"):
                raise ValueError(
                    f"{compiled_path}: compiled embedding data vocabulary does not match imported HF vocab {import_metadata['vocab_size']}"
                )
    vocab_values = values("--embedding-vocab-size")
    max_values = values("--max-seq-len")
    vocab_size = int(vocab_values[-1]) if vocab_values else 32768
    max_tokens = int(max_values[-1]) if max_values else 128
    metadata: dict[str, Any] | None = None
    if not has_compiled_data:
        manifest: str | Path | Mapping[str, Any] = manifests[0] if manifests else inline_embedding_manifest(sources)
        metadata = compile_embedding_datasets(
            manifest,
            output_dir / "embedding_data.tsv",
            vocab_size=vocab_size,
            max_tokens=max_tokens,
            tokenizer_dir=tokenizer_dir,
            architecture=(values("--embedding-architecture") or ["bert"])[-1],
        )
    if import_metadata is not None:
        metadata = dict(metadata or {})
        metadata["hf_import"] = import_metadata
    stripped: list[str] = [args[0]]
    index = 1
    removed = {"--embedding-datasets-manifest", "--embedding-dataset", "--embedding-hf-model", "--embedding-hf-revision"}
    while index < len(args):
        item = args[index]
        if item in removed:
            index += 2
            continue
        if any(item.startswith(flag + "=") for flag in removed):
            index += 1
            continue
        stripped.append(item)
        index += 1
    if not has_compiled_data and metadata is not None:
        stripped.extend(["--embedding-data", str(metadata["path"]), "--embedding-data-sha256", str(metadata["sha256"])])
    return stripped, metadata


def read_embedding_checkpoint_header(path: str | Path) -> dict[str, int]:
    checkpoint = Path(path).expanduser()
    if checkpoint.is_dir():
        checkpoint = checkpoint / "embedding_model.bin"
    with checkpoint.open("rb") as handle:
        header = handle.read(8 + 16 * 4)
    if len(header) < 36 or header[:8] not in {b"NFNEMB1\0", b"NFNEMB2\0"}:
        raise ValueError(f"{checkpoint} is not a NeuralFn embedding checkpoint")
    if header[:8] == b"NFNEMB1\0":
        version, vocab_size, hidden_dim, output_dim, max_tokens, step, adapter = struct.unpack("<7I", header[8:36])
        transformer = {"num_layers": 0, "num_heads": 0, "intermediate_dim": 0}
    else:
        values = struct.unpack("<16I", header[8:72])
        version, vocab_size, hidden_dim, output_dim, max_tokens, step, adapter = values[:7]
        transformer = {"num_layers": values[10], "num_heads": values[11], "intermediate_dim": values[12], "mask_token_id": values[15]}
    return {
        "version": version,
        "vocab_size": vocab_size,
        "hidden_dim": hidden_dim,
        "output_dim": output_dim,
        "max_tokens": max_tokens,
        "step": step,
        "adapter_type": adapter,
        **transformer,
    }
